[Rainmeter]
RightMouseUpAction=[!SkinCustomMenu]
Group=Autocomb
ContextTitle=#CURRENTCONFIG#
ContextAction=["#CURRENTPATH#"]
ContextTitle2=-
ContextAction2=
ContextTitle3=Edit variables
ContextAction3=["#CONFIGEDITOR#" "#@#Variables.inc"]
ContextTitle4=Refresh Autocomb
ContextAction4=[!RefreshGroup Autocomb]
ContextTitle5=-
ContextAction5=
ContextTitle6=Load all combs
ContextAction6=[!CommandMeasure PSRM Load]
ContextTitle7=Deactivate all combs
ContextAction7=[!CommandMeasure PSRM Unload]
ContextTitle8=-
ContextAction8=
ContextTitle9=Open skin menu
ContextAction9=[!SkinMenu]

